package main

type membership struct {
	Type int `json:"type"`
	Cost int `json:"cost"`
}

const (
	MEMBERSHIP_TYPE_NO = 0
	MEMBERSHIP_COST_NO = 0

	MEMBERSHIP_NETLIFX_TYPE_BASIC = iota + 1
	MEMBERSHIP_NETLIFX_TYPE_STANDARD
	MEMBERSHIP_NETLIFX_TYPE_PREMIUM

	MEMBERSHIP_NETLIFX_COST_STANDARD = 9_500
	MEMBERSHIP_NETLIFX_COST_BASIC    = 13_500
	MEMBERSHIP_NETLIFX_COST_PREMIUM  = 17_000
)
